/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.recuperacion;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // recuperacion de Chen 
        System.out.println("bienvenidos a mi recuperacion");
        System.out.println("les presentare las tablas de multiplicar");
        //tablas de multiplicar
    }
}
