/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.recuperacion;

import java.util.Scanner;

public class App {
     public static void main(String[]args){
    
        Scanner sc = new Scanner (System.in);
        System.out.println("Sistema para calcular notas");
        System.out.println("-----------------------------");
    }
        
    }

