/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.recuperacion;

import java.util.Scanner;

public class App {
     public static void main(String[]args){
    
        Scanner sc = new Scanner (System.in);
        // calculamos la primera nota
        System.out.println("Sistema para calcular notas");
        System.out.println("-----------------------------");
        System.out.println("Ingrese su nota referente al primer parcial: ");
        double n1 =sc.nextDouble();
        // calculamos la segunda nota 
        System.out.println("ingrese la nota del segundo parcial: ");
        double n2 =sc.nextDouble();
        // calculamos la tercera nota
        System.out.println("ingrese la tercera nota: ");
        double n3 = sc.nextDouble();
        double suma = n1+n2+n3;
        double promedio= suma/3;
         if (suma>=21 && suma<=30){// si aprueba directo
            System.out.println("El estudiante aprobo directo, su nota es :" + promedio);
        
    } else if (suma >=21 && suma >= 15){//si me pide supletorio 
            System.out.println("el estudiante debe dar un examen supletorio");
            double examen = sc.nextDouble();
            double porcentaje_promedio = promedio*0.6;
            double porcentaje_examen = examen*0.4;
            double total_examen= porcentaje_promedio+ porcentaje_examen;
            if (total_examen >=7){
                System.out.println("El estudiante aprueba con el examen final su promedio es  "+total_examen);
            }else{
                // reprueba 
                System.out.println("El estudiante reprobo con examen final;su promdio es: "+total_examen);
                
            }
    }else{
            System.out.println("El estudiante reprueba directo, el promedio es "+promedio);
             System.out.println("gracias por usar el programa");
             // fin del programa 
        }


        
    }
}


